on:
  workflow_dispatch:
  schedule:
    - cron: '16 7 * * *'
name: update-ips
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run go-generate
        run: go generate

      - name: Run tests
        run: go test -v ./...

      - name: Commit and push if changed
        run: |-
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          # if there's only 1+1 change it is just the timestamp, don't update the file
          git diff --numstat | awk 'BEGIN { OK=0; }; $1 > 1 || $2 > 1 { OK=1; }; END { if (OK) { exit(0); } else { exit(1); }}' | exit 0
          git commit -a -m "Update ip ranges" || exit 0
          git push
